services:
  redis:
    image: redis:7-alpine
    ports:
      - ${REDIS__PORT}:${REDIS__PORT}
    volumes:
      - redis_data:/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "${RABBITMQ__PORT}:${RABBITMQ__PORT}"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis_data:
  redisinsight_data:
  rabbitmq-data:

networks:
  app-network:
    driver: bridge
